apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: csi-driver-nfs
  namespace: flux-system
spec:
  interval: 10m
  path: clusters/main/kubernetes/system/csi-driver-nfs/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster

