apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:TKoJEdN2d69/r8TEyx6+eaQgZSn8L6v5KHe2OkCZE9EIC8d3+YF1h7IDHbVoYrF7ar5nnSVbaadd4cipxW3L3Is7i9Hg1qWHuw5Z+4z8PXmS/tFEY5wXe7V3c4RxiM+fOKnDPraGs4R6210ousVygLKJGaVmZmhKg68HCDnFUmEfom3JS2GHZOUOaYAIuN74IxnEWl44qDmtbIu3qRau2DjTym4q++/FKbapaMTKEwqs7HVfjDlx4mXXz6X+dOzzTxeTX8DGNTX63ZSlMDkdZ+qV7dzBmA3ahgM58LjU2EFRW7/THdapFvrDJ07QO8BUUgy1HEKLz4GJpCH3Jj8Cyo4fMb1uIG4Ey5iXB+0Q3fMlGHMSSbEZ4X/O4498iDM6,iv:ycBIG2RDkBI+5xQt26LC/LzKKSxPbly9eBVHsP7FM0g=,tag:RKvt7u+u3TrzELzAZmc7YQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:/g13xQ8596A0JVUkVCB44BIQAupERBGTlF5vzXrLzT2iboV7Do7Vs5Pa/dJ9nfF4RZV74YHIehidLapRozdUaoSeCeGRTQIWBtGeOwQmgX/MeZSe1NJ7GgSast/g7QBvDEPHqz/5+qGV1pQ2BEtO5zAko7GjNCfp8lVPnHnm4w0UvQ+7dWawnx+vbl5ndTJV1KqGAnjTnabMU3oesQgfKs9AaQsa/bLvYNR025EgSE/tJUY0gf6ZUp5+12z4l14ouHpvPycx4xlyIlJD4g==,iv:vzs1kQNm0MEXMflkSMKe8xNuMUqLZ2MkIDSgc0NOdwo=,tag:l5PQMwR+MFRoBh7tPzFqTw==,type:str]
    known_hosts: ENC[AES256_GCM,data:n/ZZ0zskNGzahMo9kQetd8B0luITiPPH+F4LNe+LctwgAqFRM/mnwYBpg5Wps8Yb5HMHnDWgzb8LQWyjDTCBX2hW9ep3+T3WfyAnqpYbMTuIaSt6INEKanimiEpiDwpJaLEpJdGCYGIwX3+c9wlrSN9RCSomzZMNZXDRq5+GmPbXznb3AxaCvtzsJR7Nhu6upCJ5mySalN93gWs3hjmsBH11DallZVab29JA,iv:ekqkWf2xMYR4r/ZTatqPLgS50Fjf8v58wns9ESc09xw=,tag:v6rFV2cz4yAkPZNw+hANtg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z22mce5z97dh9zgcpa339e43tcxaamn5vdhndly23nj3kry2p4hqvu30fe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEVWFvSEN4YUxPdysyMzdu
            emx3Y01NN2V0ZHlNUWdubUVNMU1lUzVzR2hvCk9oNWh0OVpGTE1McUxyL3QxV0JL
            TWdpZHFFNnJFN2ZuT0J5N0lBZVlBK3cKLS0tIEhEK0QxRGhFWFNkaDdqYUtLMWZB
            amdEMDY5L1ljNlM2UUZFVGRSOXVYQU0KQ9jrN2MZNqjkeNWuDZlt5TtLwaFyhxa7
            Y3+5h2EoTKlsX0Q96Zb8fkZa2MxD0yMOxRUvSxCL2hXRla1cNaCoVA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-22T18:45:53Z"
    mac: ENC[AES256_GCM,data:HDvj+Vgxhf2omVrM3R83H3sKEiLmPuydkb/3Elz9yMcFSJxdVdYGl98wHZwKqffhjkUYvhbz2A3Am2zq8qOJqsi4kPePhn3rhfw2b6zjazU/zsHEt7huyjAs6D6q4v/MXtEC3FFJKTWiCwsamrYnfo77vlQRSuUBpmosH7Tx8M4=,iv:PHHFElo0PzSVT3AwALNgq06ATAQQGHkWo+Q3J9gO4/E=,tag:PD51+JDC+rgVmnk//HbuEw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
