apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:X/syap1AtlO1l17M9dIcIQfmXJVeB87dJh45FoD0Upp1lPjU9Cp8JFp3SPRI/eLiR82Mxw0ho/XKN0340RZKMapm+dcVj8nwYHaGK6Q0leYS8LOZacfspyb5xpCxZbMi+az8fcSb04roqPrSzV871Q9BTrL6FzJTUiHbCMXsNIwk0ASXdSAbTjloyMeS2g7yMot9zyMO4NHL11PElOD1Zla2kHVjLGdFvcE7d0NP6M4WoguY/3OSOUt9jVHOZJc55ONaBQPR7+JD1tuz0DRjkqPOnzn79e1l2FnlBAp0ip/rnQ+in3nP4ANHLdsOvgwmOTcsW4dX4zhc79Ms8J5o6K+5Kczp6+XQDt/brHHRp6fVSKm9YL0ZH4crmcNWpDPf,iv:qaDfouzqSoWP3SlslLGXkrslJpffakgmTSG48opd0jc=,tag:BoQYYEsvSZB/Gxi8ZavS+w==,type:str]
    identity.pub: ENC[AES256_GCM,data:TqwbAjL10wXvCM4qzOtcJss2tZOAWezrrRedTnGofmwKwGeev+z5QOom2sRsBAbBvAtExp6yUNG7OAHLCz2EAhOWaJIz/BaF7kmIJ6mkyvz+xbvyB8duXC8eNlAoL0PF0ZCpXFp9c6JnhWXc7P0QXAkQFunuIVwdCKfCSYFQPXdwymAZ+6x9fGBVH2vOL1Z2r2FMEv2hgXzfEvctCNHFjHDDpovXocCLWMGLsaD0qErp/Sz4ELlaTquRk4lIvzAmo9tHjCQAQX/L3vaOIA==,iv:2uTQpIQoaTIpo7VxfEp7qNWgC3xuGOPCDY6zFGrhhgw=,tag:Icp1SmOOCG55ySLhjh6aBw==,type:str]
    known_hosts: ENC[AES256_GCM,data:6OitHhxDlY+jW+dp2+JL0CC/Z/WaKNiHHln7S0dEqNCzlN6Eka3KZULrsKMD01G74xzBHg32X3fEV9XmPmn4NTTvO9d2JJbE3ifuOKGXpLqQQTLkQJQuK8InEdcWs9khRUKTf3ij5Hzf19LU9qoBCcg8Xwey167yfYFCSuV8YrJB+F+GgDvVtC9OGfkTSRB8XvbiWtBNa3kZgodK8m4TZIgeR4ItYWlDY9/D,iv:INGHCJm87F2xbGF0eFYiYtlieU8g5NS5youdtuVem4M=,tag:PnZa53w8Mc2Lww9N1ozBQA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z22mce5z97dh9zgcpa339e43tcxaamn5vdhndly23nj3kry2p4hqvu30fe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2K0VuSTd5Uk1TTis5VWRq
            bkpBU1JHazRMOGpQdTJBU09pSTZYZmtXcEVVClp4ekNBMG5NRWNRZStzNTJmeFRX
            c21JclZNMFdmeDczYlpQSjhsbEdYTHMKLS0tIHcrOGQ2c3dUaUJnaUdmZFQ1M29W
            YTdLNEszWVNNdWlWQUlhM2k4bG5CUE0KcUiqTaUk97sZWH4lv5lIiFO168KtEcfl
            TqL1Vn/QQZs9NjvNn0P1FywzVX1bPNQCWKotwsd+erNl8Tr0GhTDsw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-22T18:23:05Z"
    mac: ENC[AES256_GCM,data:Ir3aI3nbkkFOXRX0UYAXGWXp0IFvhHXiJm8HA2NoKdiocyMjKOLH9gmmG9kQLH5h+kpTPLO3Euk3CzOr2Bj6of92j7ESq/m7rw567n4Tn8Wt6BAU9fuF7cusYfg6uvbWBuMDYQp6UNp5c69saDyA4VGGK521HeQrnMlJ2dLf32s=,iv:KhuL/TYUNMHzHPiZQxV2DTsXXicZdJO8ah4rYfjRmOA=,tag:3vO4G8NQkxL7vaAtrbt3yQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
