metadata:
    name: clusterissuer
    namespace: clusterissuer
spec:
    interval: 15m
    chart:
        spec:
            chart: clusterissuer
            version: 9.2.0
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
    releaseName: clusterissuer
    values:
        clusterIssuer:
            ACME:
                - name: cert
                  email: zachbomb@gmail.com
                  server: https://acme-v02.api.letsencrypt.org/directory
                  type: cloudflare
                  cfapitoken: 6v76VhIdmSdtLYvJahygY9oMcttcevsECj8ZULA3
        customMetrics:
            enabled: true
        manifestManager:
            enabled: true
        operator:
            cert-manager:
                namespace: cert-manager
        release_name: clusterissuer
        service:
            main:
                enabled: false
                ports:
                    main:
                        enabled: false
                        port: 9999
        workload:
            main:
                enabled: false
                podSpec:
                    containers:
                        main:
                            enabled: false
                            probes:
                                liveness:
                                    enabled: false
                                readiness:
                                    enabled: false
                                startup:
                                    enabled: false
