metadata:
    name: prowlarr
    namespace: networking
spec:
    interval: 15m
    chart:
        spec:
            chart: external-service
            version: 14.1.2
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
    releaseName: prowlarr
    values:
        ingress:
            main:
                annotations:
                    traefik.frontend.passHostHeader: "false"
                enabled: true
                hosts:
                    - host: prowlarr.sf.wethecommon.com
                      paths:
                        - path: /
                          pathType: Prefix
                ingressClassName: ""
                integrations:
                    certManager:
                        certificateIssuer: cert
                        enabled: true
                    homepage:
                        enabled: false
                    traefik:
                        allowCors: false
                        enabled: true
                        entrypoints:
                            - websecure
        release_name: external-service
        service:
            main:
                enabled: true
                externalIP: 192.168.10.10
                ports:
                    main:
                        enabled: true
                        port: 9696
                        protocol: http
                type: ExternalIP
                useSlice: false
        workload:
            main:
                enabled: false
                podSpec:
                    containers:
                        main: {}
